# Makefile.in generated by automake 1.18.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2025 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
am__rm_f = rm -f $(am__rm_f_notfound)
am__rm_rf = rm -rf $(am__rm_f_notfound)
pkgdatadir = $(datadir)/1984
pkgincludedir = $(includedir)/1984
pkglibdir = $(libdir)/1984
pkglibexecdir = $(libexecdir)/1984
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = 1984$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_check_compile_flag.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_1984_OBJECTS = src/1984-config.$(OBJEXT) src/1984-cpc.$(OBJEXT) \
	src/1984-monitor.$(OBJEXT) src/1984-net4cpc.$(OBJEXT) \
	src/1984-z80dis.$(OBJEXT) src/1984-crtc.$(OBJEXT) \
	src/1984-disk.$(OBJEXT) src/1984-display.$(OBJEXT) \
	src/1984-fdc.$(OBJEXT) src/1984-gate_array.$(OBJEXT) \
	src/1984-joy.$(OBJEXT) src/1984-kbd.$(OBJEXT) \
	src/1984-main.$(OBJEXT) src/1984-mem.$(OBJEXT) \
	src/1984-overlay.$(OBJEXT) src/1984-paste.$(OBJEXT) \
	src/1984-ppi.$(OBJEXT) src/1984-psg.$(OBJEXT) \
	src/1984-rtc.$(OBJEXT) src/1984-ide.$(OBJEXT) src/1984-z80.$(OBJEXT)
1984_OBJECTS = $(am_1984_OBJECTS)
am__DEPENDENCIES_1 =
1984_DEPENDENCIES = $(am__DEPENDENCIES_1)
1984_LINK = $(CCLD) $(1984_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/build-aux/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = src/$(DEPDIR)/1984-config.Po \
	src/$(DEPDIR)/1984-cpc.Po src/$(DEPDIR)/1984-crtc.Po \
	src/$(DEPDIR)/1984-disk.Po src/$(DEPDIR)/1984-display.Po \
	src/$(DEPDIR)/1984-fdc.Po src/$(DEPDIR)/1984-gate_array.Po \
	src/$(DEPDIR)/1984-joy.Po src/$(DEPDIR)/1984-kbd.Po \
	src/$(DEPDIR)/1984-main.Po src/$(DEPDIR)/1984-mem.Po \
	src/$(DEPDIR)/1984-monitor.Po src/$(DEPDIR)/1984-net4cpc.Po \
	src/$(DEPDIR)/1984-overlay.Po src/$(DEPDIR)/1984-paste.Po \
	src/$(DEPDIR)/1984-ppi.Po src/$(DEPDIR)/1984-psg.Po \
	src/$(DEPDIR)/1984-rtc.Po src/$(DEPDIR)/1984-ide.Po src/$(DEPDIR)/1984-z80.Po \
	src/$(DEPDIR)/1984-z80dis.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(1984_SOURCES)
DIST_SOURCES = $(1984_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in \
	$(top_srcdir)/build-aux/compile \
	$(top_srcdir)/build-aux/depcomp \
	$(top_srcdir)/build-aux/install-sh \
	$(top_srcdir)/build-aux/missing README.md build-aux/compile \
	build-aux/depcomp build-aux/install-sh build-aux/missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -700 -exec chmod u+rwx {} ';' \
      ; rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = -9
DIST_TARGETS = dist-gzip
# Exists only to be overridden by the user if desired.
AM_DISTCHECK_DVI_TARGET = dvi
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = \
  find . \( -type f -a \! \
            \( -name .nfs* -o -name .smb* -o -name .__afs* \) \) -print
ACLOCAL = ${SHELL} '/var/home/salvogendut/Dev/1984/build-aux/missing' aclocal-1.18
AMTAR = $${TAR-tar}
AM_CFLAGS =  -std=c11
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} '/var/home/salvogendut/Dev/1984/build-aux/missing' autoconf
AUTOHEADER = ${SHELL} '/var/home/salvogendut/Dev/1984/build-aux/missing' autoheader
AUTOMAKE = ${SHELL} '/var/home/salvogendut/Dev/1984/build-aux/missing' automake-1.18
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CSCOPE = cscope
CTAGS = ctags
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"1984\" -DPACKAGE_TARNAME=\"1984\" -DPACKAGE_VERSION=\"0.3.0\" -DPACKAGE_STRING=\"1984\ 0.3.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"1984\" -DVERSION=\"0.3.0\" -DHAVE_LIBM=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
ETAGS = etags
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lm 
LTLIBOBJS = 
MAKEINFO = ${SHELL} '/var/home/salvogendut/Dev/1984/build-aux/missing' makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = 1984
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 1984
PACKAGE_STRING = 1984 0.3.0
PACKAGE_TARNAME = 1984
PACKAGE_URL = 
PACKAGE_VERSION = 0.3.0
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
SDL3_CFLAGS = -I/usr/include
SDL3_LIBS = /usr/lib64/libSDL3.so.0
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.3.0
abs_builddir = /var/home/salvogendut/Dev/1984
abs_srcdir = /var/home/salvogendut/Dev/1984
abs_top_builddir = /var/home/salvogendut/Dev/1984
abs_top_srcdir = /var/home/salvogendut/Dev/1984
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__rm_f_notfound = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
am__xargs_n = xargs -n
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /var/home/salvogendut/Dev/1984/build-aux/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
1984_SOURCES = \
	src/config.c \
	src/cpc.c \
	src/monitor.c \
	src/net4cpc.c \
	src/z80dis.c \
	src/crtc.c \
	src/disk.c \
	src/display.c \
	src/fdc.c \
	src/gate_array.c \
	src/joy.c \
	src/kbd.c \
	src/main.c \
	src/mem.c \
	src/overlay.c \
	src/paste.c \
	src/ppi.c \
	src/psg.c \
	src/rtc.c \
	src/ide.c \
	src/z80.c

1984_CFLAGS = $(AM_CFLAGS) $(SDL3_CFLAGS) -Wall -Wextra
1984_LDADD = $(SDL3_LIBS) -lm

# Keep the hand-written Makefile usable alongside autotools
EXTRA_DIST = Makefile
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && $(am__rm_f) $$files

clean-binPROGRAMS:
	-$(am__rm_f) $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: >>src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: >>src/$(DEPDIR)/$(am__dirstamp)
src/1984-config.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-cpc.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-monitor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-net4cpc.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-z80dis.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-crtc.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-disk.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-display.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-fdc.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-gate_array.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-joy.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-kbd.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-main.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-mem.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-overlay.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-paste.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-ppi.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-psg.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-rtc.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-ide.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/1984-z80.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

1984$(EXEEXT): $(1984_OBJECTS) $(1984_DEPENDENCIES) $(EXTRA_1984_DEPENDENCIES) 
	@rm -f 1984$(EXEEXT)
	$(AM_V_CCLD)$(1984_LINK) $(1984_OBJECTS) $(1984_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/1984-config.Po # am--include-marker
include src/$(DEPDIR)/1984-cpc.Po # am--include-marker
include src/$(DEPDIR)/1984-crtc.Po # am--include-marker
include src/$(DEPDIR)/1984-disk.Po # am--include-marker
include src/$(DEPDIR)/1984-display.Po # am--include-marker
include src/$(DEPDIR)/1984-fdc.Po # am--include-marker
include src/$(DEPDIR)/1984-gate_array.Po # am--include-marker
include src/$(DEPDIR)/1984-joy.Po # am--include-marker
include src/$(DEPDIR)/1984-kbd.Po # am--include-marker
include src/$(DEPDIR)/1984-main.Po # am--include-marker
include src/$(DEPDIR)/1984-mem.Po # am--include-marker
include src/$(DEPDIR)/1984-monitor.Po # am--include-marker
include src/$(DEPDIR)/1984-net4cpc.Po # am--include-marker
include src/$(DEPDIR)/1984-overlay.Po # am--include-marker
include src/$(DEPDIR)/1984-paste.Po # am--include-marker
include src/$(DEPDIR)/1984-ppi.Po # am--include-marker
include src/$(DEPDIR)/1984-psg.Po # am--include-marker
include src/$(DEPDIR)/1984-rtc.Po # am--include-marker
include src/$(DEPDIR)/1984-ide.Po # am--include-marker
include src/$(DEPDIR)/1984-z80.Po # am--include-marker
include src/$(DEPDIR)/1984-z80dis.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@: >>$@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/1984-config.o: src/config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-config.o -MD -MP -MF src/$(DEPDIR)/1984-config.Tpo -c -o src/1984-config.o `test -f 'src/config.c' || echo '$(srcdir)/'`src/config.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-config.Tpo src/$(DEPDIR)/1984-config.Po
#	$(AM_V_CC)source='src/config.c' object='src/1984-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-config.o `test -f 'src/config.c' || echo '$(srcdir)/'`src/config.c

src/1984-config.obj: src/config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-config.obj -MD -MP -MF src/$(DEPDIR)/1984-config.Tpo -c -o src/1984-config.obj `if test -f 'src/config.c'; then $(CYGPATH_W) 'src/config.c'; else $(CYGPATH_W) '$(srcdir)/src/config.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-config.Tpo src/$(DEPDIR)/1984-config.Po
#	$(AM_V_CC)source='src/config.c' object='src/1984-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-config.obj `if test -f 'src/config.c'; then $(CYGPATH_W) 'src/config.c'; else $(CYGPATH_W) '$(srcdir)/src/config.c'; fi`

src/1984-cpc.o: src/cpc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-cpc.o -MD -MP -MF src/$(DEPDIR)/1984-cpc.Tpo -c -o src/1984-cpc.o `test -f 'src/cpc.c' || echo '$(srcdir)/'`src/cpc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-cpc.Tpo src/$(DEPDIR)/1984-cpc.Po
#	$(AM_V_CC)source='src/cpc.c' object='src/1984-cpc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-cpc.o `test -f 'src/cpc.c' || echo '$(srcdir)/'`src/cpc.c

src/1984-cpc.obj: src/cpc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-cpc.obj -MD -MP -MF src/$(DEPDIR)/1984-cpc.Tpo -c -o src/1984-cpc.obj `if test -f 'src/cpc.c'; then $(CYGPATH_W) 'src/cpc.c'; else $(CYGPATH_W) '$(srcdir)/src/cpc.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-cpc.Tpo src/$(DEPDIR)/1984-cpc.Po
#	$(AM_V_CC)source='src/cpc.c' object='src/1984-cpc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-cpc.obj `if test -f 'src/cpc.c'; then $(CYGPATH_W) 'src/cpc.c'; else $(CYGPATH_W) '$(srcdir)/src/cpc.c'; fi`

src/1984-monitor.o: src/monitor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-monitor.o -MD -MP -MF src/$(DEPDIR)/1984-monitor.Tpo -c -o src/1984-monitor.o `test -f 'src/monitor.c' || echo '$(srcdir)/'`src/monitor.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-monitor.Tpo src/$(DEPDIR)/1984-monitor.Po
#	$(AM_V_CC)source='src/monitor.c' object='src/1984-monitor.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-monitor.o `test -f 'src/monitor.c' || echo '$(srcdir)/'`src/monitor.c

src/1984-monitor.obj: src/monitor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-monitor.obj -MD -MP -MF src/$(DEPDIR)/1984-monitor.Tpo -c -o src/1984-monitor.obj `if test -f 'src/monitor.c'; then $(CYGPATH_W) 'src/monitor.c'; else $(CYGPATH_W) '$(srcdir)/src/monitor.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-monitor.Tpo src/$(DEPDIR)/1984-monitor.Po
#	$(AM_V_CC)source='src/monitor.c' object='src/1984-monitor.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-monitor.obj `if test -f 'src/monitor.c'; then $(CYGPATH_W) 'src/monitor.c'; else $(CYGPATH_W) '$(srcdir)/src/monitor.c'; fi`

src/1984-net4cpc.o: src/net4cpc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-net4cpc.o -MD -MP -MF src/$(DEPDIR)/1984-net4cpc.Tpo -c -o src/1984-net4cpc.o `test -f 'src/net4cpc.c' || echo '$(srcdir)/'`src/net4cpc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-net4cpc.Tpo src/$(DEPDIR)/1984-net4cpc.Po
#	$(AM_V_CC)source='src/net4cpc.c' object='src/1984-net4cpc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-net4cpc.o `test -f 'src/net4cpc.c' || echo '$(srcdir)/'`src/net4cpc.c

src/1984-net4cpc.obj: src/net4cpc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-net4cpc.obj -MD -MP -MF src/$(DEPDIR)/1984-net4cpc.Tpo -c -o src/1984-net4cpc.obj `if test -f 'src/net4cpc.c'; then $(CYGPATH_W) 'src/net4cpc.c'; else $(CYGPATH_W) '$(srcdir)/src/net4cpc.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-net4cpc.Tpo src/$(DEPDIR)/1984-net4cpc.Po
#	$(AM_V_CC)source='src/net4cpc.c' object='src/1984-net4cpc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-net4cpc.obj `if test -f 'src/net4cpc.c'; then $(CYGPATH_W) 'src/net4cpc.c'; else $(CYGPATH_W) '$(srcdir)/src/net4cpc.c'; fi`

src/1984-z80dis.o: src/z80dis.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-z80dis.o -MD -MP -MF src/$(DEPDIR)/1984-z80dis.Tpo -c -o src/1984-z80dis.o `test -f 'src/z80dis.c' || echo '$(srcdir)/'`src/z80dis.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-z80dis.Tpo src/$(DEPDIR)/1984-z80dis.Po
#	$(AM_V_CC)source='src/z80dis.c' object='src/1984-z80dis.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-z80dis.o `test -f 'src/z80dis.c' || echo '$(srcdir)/'`src/z80dis.c

src/1984-z80dis.obj: src/z80dis.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-z80dis.obj -MD -MP -MF src/$(DEPDIR)/1984-z80dis.Tpo -c -o src/1984-z80dis.obj `if test -f 'src/z80dis.c'; then $(CYGPATH_W) 'src/z80dis.c'; else $(CYGPATH_W) '$(srcdir)/src/z80dis.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-z80dis.Tpo src/$(DEPDIR)/1984-z80dis.Po
#	$(AM_V_CC)source='src/z80dis.c' object='src/1984-z80dis.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-z80dis.obj `if test -f 'src/z80dis.c'; then $(CYGPATH_W) 'src/z80dis.c'; else $(CYGPATH_W) '$(srcdir)/src/z80dis.c'; fi`

src/1984-crtc.o: src/crtc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-crtc.o -MD -MP -MF src/$(DEPDIR)/1984-crtc.Tpo -c -o src/1984-crtc.o `test -f 'src/crtc.c' || echo '$(srcdir)/'`src/crtc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-crtc.Tpo src/$(DEPDIR)/1984-crtc.Po
#	$(AM_V_CC)source='src/crtc.c' object='src/1984-crtc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-crtc.o `test -f 'src/crtc.c' || echo '$(srcdir)/'`src/crtc.c

src/1984-crtc.obj: src/crtc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-crtc.obj -MD -MP -MF src/$(DEPDIR)/1984-crtc.Tpo -c -o src/1984-crtc.obj `if test -f 'src/crtc.c'; then $(CYGPATH_W) 'src/crtc.c'; else $(CYGPATH_W) '$(srcdir)/src/crtc.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-crtc.Tpo src/$(DEPDIR)/1984-crtc.Po
#	$(AM_V_CC)source='src/crtc.c' object='src/1984-crtc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-crtc.obj `if test -f 'src/crtc.c'; then $(CYGPATH_W) 'src/crtc.c'; else $(CYGPATH_W) '$(srcdir)/src/crtc.c'; fi`

src/1984-disk.o: src/disk.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-disk.o -MD -MP -MF src/$(DEPDIR)/1984-disk.Tpo -c -o src/1984-disk.o `test -f 'src/disk.c' || echo '$(srcdir)/'`src/disk.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-disk.Tpo src/$(DEPDIR)/1984-disk.Po
#	$(AM_V_CC)source='src/disk.c' object='src/1984-disk.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-disk.o `test -f 'src/disk.c' || echo '$(srcdir)/'`src/disk.c

src/1984-disk.obj: src/disk.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-disk.obj -MD -MP -MF src/$(DEPDIR)/1984-disk.Tpo -c -o src/1984-disk.obj `if test -f 'src/disk.c'; then $(CYGPATH_W) 'src/disk.c'; else $(CYGPATH_W) '$(srcdir)/src/disk.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-disk.Tpo src/$(DEPDIR)/1984-disk.Po
#	$(AM_V_CC)source='src/disk.c' object='src/1984-disk.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-disk.obj `if test -f 'src/disk.c'; then $(CYGPATH_W) 'src/disk.c'; else $(CYGPATH_W) '$(srcdir)/src/disk.c'; fi`

src/1984-display.o: src/display.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-display.o -MD -MP -MF src/$(DEPDIR)/1984-display.Tpo -c -o src/1984-display.o `test -f 'src/display.c' || echo '$(srcdir)/'`src/display.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-display.Tpo src/$(DEPDIR)/1984-display.Po
#	$(AM_V_CC)source='src/display.c' object='src/1984-display.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-display.o `test -f 'src/display.c' || echo '$(srcdir)/'`src/display.c

src/1984-display.obj: src/display.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-display.obj -MD -MP -MF src/$(DEPDIR)/1984-display.Tpo -c -o src/1984-display.obj `if test -f 'src/display.c'; then $(CYGPATH_W) 'src/display.c'; else $(CYGPATH_W) '$(srcdir)/src/display.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-display.Tpo src/$(DEPDIR)/1984-display.Po
#	$(AM_V_CC)source='src/display.c' object='src/1984-display.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-display.obj `if test -f 'src/display.c'; then $(CYGPATH_W) 'src/display.c'; else $(CYGPATH_W) '$(srcdir)/src/display.c'; fi`

src/1984-fdc.o: src/fdc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-fdc.o -MD -MP -MF src/$(DEPDIR)/1984-fdc.Tpo -c -o src/1984-fdc.o `test -f 'src/fdc.c' || echo '$(srcdir)/'`src/fdc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-fdc.Tpo src/$(DEPDIR)/1984-fdc.Po
#	$(AM_V_CC)source='src/fdc.c' object='src/1984-fdc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-fdc.o `test -f 'src/fdc.c' || echo '$(srcdir)/'`src/fdc.c

src/1984-fdc.obj: src/fdc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-fdc.obj -MD -MP -MF src/$(DEPDIR)/1984-fdc.Tpo -c -o src/1984-fdc.obj `if test -f 'src/fdc.c'; then $(CYGPATH_W) 'src/fdc.c'; else $(CYGPATH_W) '$(srcdir)/src/fdc.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-fdc.Tpo src/$(DEPDIR)/1984-fdc.Po
#	$(AM_V_CC)source='src/fdc.c' object='src/1984-fdc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-fdc.obj `if test -f 'src/fdc.c'; then $(CYGPATH_W) 'src/fdc.c'; else $(CYGPATH_W) '$(srcdir)/src/fdc.c'; fi`

src/1984-gate_array.o: src/gate_array.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-gate_array.o -MD -MP -MF src/$(DEPDIR)/1984-gate_array.Tpo -c -o src/1984-gate_array.o `test -f 'src/gate_array.c' || echo '$(srcdir)/'`src/gate_array.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-gate_array.Tpo src/$(DEPDIR)/1984-gate_array.Po
#	$(AM_V_CC)source='src/gate_array.c' object='src/1984-gate_array.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-gate_array.o `test -f 'src/gate_array.c' || echo '$(srcdir)/'`src/gate_array.c

src/1984-gate_array.obj: src/gate_array.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-gate_array.obj -MD -MP -MF src/$(DEPDIR)/1984-gate_array.Tpo -c -o src/1984-gate_array.obj `if test -f 'src/gate_array.c'; then $(CYGPATH_W) 'src/gate_array.c'; else $(CYGPATH_W) '$(srcdir)/src/gate_array.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-gate_array.Tpo src/$(DEPDIR)/1984-gate_array.Po
#	$(AM_V_CC)source='src/gate_array.c' object='src/1984-gate_array.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-gate_array.obj `if test -f 'src/gate_array.c'; then $(CYGPATH_W) 'src/gate_array.c'; else $(CYGPATH_W) '$(srcdir)/src/gate_array.c'; fi`

src/1984-joy.o: src/joy.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-joy.o -MD -MP -MF src/$(DEPDIR)/1984-joy.Tpo -c -o src/1984-joy.o `test -f 'src/joy.c' || echo '$(srcdir)/'`src/joy.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-joy.Tpo src/$(DEPDIR)/1984-joy.Po
#	$(AM_V_CC)source='src/joy.c' object='src/1984-joy.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-joy.o `test -f 'src/joy.c' || echo '$(srcdir)/'`src/joy.c

src/1984-joy.obj: src/joy.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-joy.obj -MD -MP -MF src/$(DEPDIR)/1984-joy.Tpo -c -o src/1984-joy.obj `if test -f 'src/joy.c'; then $(CYGPATH_W) 'src/joy.c'; else $(CYGPATH_W) '$(srcdir)/src/joy.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-joy.Tpo src/$(DEPDIR)/1984-joy.Po
#	$(AM_V_CC)source='src/joy.c' object='src/1984-joy.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-joy.obj `if test -f 'src/joy.c'; then $(CYGPATH_W) 'src/joy.c'; else $(CYGPATH_W) '$(srcdir)/src/joy.c'; fi`

src/1984-kbd.o: src/kbd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-kbd.o -MD -MP -MF src/$(DEPDIR)/1984-kbd.Tpo -c -o src/1984-kbd.o `test -f 'src/kbd.c' || echo '$(srcdir)/'`src/kbd.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-kbd.Tpo src/$(DEPDIR)/1984-kbd.Po
#	$(AM_V_CC)source='src/kbd.c' object='src/1984-kbd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-kbd.o `test -f 'src/kbd.c' || echo '$(srcdir)/'`src/kbd.c

src/1984-kbd.obj: src/kbd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-kbd.obj -MD -MP -MF src/$(DEPDIR)/1984-kbd.Tpo -c -o src/1984-kbd.obj `if test -f 'src/kbd.c'; then $(CYGPATH_W) 'src/kbd.c'; else $(CYGPATH_W) '$(srcdir)/src/kbd.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-kbd.Tpo src/$(DEPDIR)/1984-kbd.Po
#	$(AM_V_CC)source='src/kbd.c' object='src/1984-kbd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-kbd.obj `if test -f 'src/kbd.c'; then $(CYGPATH_W) 'src/kbd.c'; else $(CYGPATH_W) '$(srcdir)/src/kbd.c'; fi`

src/1984-main.o: src/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-main.o -MD -MP -MF src/$(DEPDIR)/1984-main.Tpo -c -o src/1984-main.o `test -f 'src/main.c' || echo '$(srcdir)/'`src/main.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-main.Tpo src/$(DEPDIR)/1984-main.Po
#	$(AM_V_CC)source='src/main.c' object='src/1984-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-main.o `test -f 'src/main.c' || echo '$(srcdir)/'`src/main.c

src/1984-main.obj: src/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-main.obj -MD -MP -MF src/$(DEPDIR)/1984-main.Tpo -c -o src/1984-main.obj `if test -f 'src/main.c'; then $(CYGPATH_W) 'src/main.c'; else $(CYGPATH_W) '$(srcdir)/src/main.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-main.Tpo src/$(DEPDIR)/1984-main.Po
#	$(AM_V_CC)source='src/main.c' object='src/1984-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-main.obj `if test -f 'src/main.c'; then $(CYGPATH_W) 'src/main.c'; else $(CYGPATH_W) '$(srcdir)/src/main.c'; fi`

src/1984-mem.o: src/mem.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-mem.o -MD -MP -MF src/$(DEPDIR)/1984-mem.Tpo -c -o src/1984-mem.o `test -f 'src/mem.c' || echo '$(srcdir)/'`src/mem.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-mem.Tpo src/$(DEPDIR)/1984-mem.Po
#	$(AM_V_CC)source='src/mem.c' object='src/1984-mem.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-mem.o `test -f 'src/mem.c' || echo '$(srcdir)/'`src/mem.c

src/1984-mem.obj: src/mem.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-mem.obj -MD -MP -MF src/$(DEPDIR)/1984-mem.Tpo -c -o src/1984-mem.obj `if test -f 'src/mem.c'; then $(CYGPATH_W) 'src/mem.c'; else $(CYGPATH_W) '$(srcdir)/src/mem.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-mem.Tpo src/$(DEPDIR)/1984-mem.Po
#	$(AM_V_CC)source='src/mem.c' object='src/1984-mem.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-mem.obj `if test -f 'src/mem.c'; then $(CYGPATH_W) 'src/mem.c'; else $(CYGPATH_W) '$(srcdir)/src/mem.c'; fi`

src/1984-overlay.o: src/overlay.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-overlay.o -MD -MP -MF src/$(DEPDIR)/1984-overlay.Tpo -c -o src/1984-overlay.o `test -f 'src/overlay.c' || echo '$(srcdir)/'`src/overlay.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-overlay.Tpo src/$(DEPDIR)/1984-overlay.Po
#	$(AM_V_CC)source='src/overlay.c' object='src/1984-overlay.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-overlay.o `test -f 'src/overlay.c' || echo '$(srcdir)/'`src/overlay.c

src/1984-overlay.obj: src/overlay.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-overlay.obj -MD -MP -MF src/$(DEPDIR)/1984-overlay.Tpo -c -o src/1984-overlay.obj `if test -f 'src/overlay.c'; then $(CYGPATH_W) 'src/overlay.c'; else $(CYGPATH_W) '$(srcdir)/src/overlay.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-overlay.Tpo src/$(DEPDIR)/1984-overlay.Po
#	$(AM_V_CC)source='src/overlay.c' object='src/1984-overlay.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-overlay.obj `if test -f 'src/overlay.c'; then $(CYGPATH_W) 'src/overlay.c'; else $(CYGPATH_W) '$(srcdir)/src/overlay.c'; fi`

src/1984-paste.o: src/paste.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-paste.o -MD -MP -MF src/$(DEPDIR)/1984-paste.Tpo -c -o src/1984-paste.o `test -f 'src/paste.c' || echo '$(srcdir)/'`src/paste.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-paste.Tpo src/$(DEPDIR)/1984-paste.Po
#	$(AM_V_CC)source='src/paste.c' object='src/1984-paste.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-paste.o `test -f 'src/paste.c' || echo '$(srcdir)/'`src/paste.c

src/1984-paste.obj: src/paste.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-paste.obj -MD -MP -MF src/$(DEPDIR)/1984-paste.Tpo -c -o src/1984-paste.obj `if test -f 'src/paste.c'; then $(CYGPATH_W) 'src/paste.c'; else $(CYGPATH_W) '$(srcdir)/src/paste.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-paste.Tpo src/$(DEPDIR)/1984-paste.Po
#	$(AM_V_CC)source='src/paste.c' object='src/1984-paste.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-paste.obj `if test -f 'src/paste.c'; then $(CYGPATH_W) 'src/paste.c'; else $(CYGPATH_W) '$(srcdir)/src/paste.c'; fi`

src/1984-ppi.o: src/ppi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-ppi.o -MD -MP -MF src/$(DEPDIR)/1984-ppi.Tpo -c -o src/1984-ppi.o `test -f 'src/ppi.c' || echo '$(srcdir)/'`src/ppi.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-ppi.Tpo src/$(DEPDIR)/1984-ppi.Po
#	$(AM_V_CC)source='src/ppi.c' object='src/1984-ppi.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-ppi.o `test -f 'src/ppi.c' || echo '$(srcdir)/'`src/ppi.c

src/1984-ppi.obj: src/ppi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-ppi.obj -MD -MP -MF src/$(DEPDIR)/1984-ppi.Tpo -c -o src/1984-ppi.obj `if test -f 'src/ppi.c'; then $(CYGPATH_W) 'src/ppi.c'; else $(CYGPATH_W) '$(srcdir)/src/ppi.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-ppi.Tpo src/$(DEPDIR)/1984-ppi.Po
#	$(AM_V_CC)source='src/ppi.c' object='src/1984-ppi.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-ppi.obj `if test -f 'src/ppi.c'; then $(CYGPATH_W) 'src/ppi.c'; else $(CYGPATH_W) '$(srcdir)/src/ppi.c'; fi`

src/1984-psg.o: src/psg.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-psg.o -MD -MP -MF src/$(DEPDIR)/1984-psg.Tpo -c -o src/1984-psg.o `test -f 'src/psg.c' || echo '$(srcdir)/'`src/psg.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-psg.Tpo src/$(DEPDIR)/1984-psg.Po
#	$(AM_V_CC)source='src/psg.c' object='src/1984-psg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-psg.o `test -f 'src/psg.c' || echo '$(srcdir)/'`src/psg.c

src/1984-psg.obj: src/psg.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-psg.obj -MD -MP -MF src/$(DEPDIR)/1984-psg.Tpo -c -o src/1984-psg.obj `if test -f 'src/psg.c'; then $(CYGPATH_W) 'src/psg.c'; else $(CYGPATH_W) '$(srcdir)/src/psg.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-psg.Tpo src/$(DEPDIR)/1984-psg.Po
#	$(AM_V_CC)source='src/psg.c' object='src/1984-psg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-psg.obj `if test -f 'src/psg.c'; then $(CYGPATH_W) 'src/psg.c'; else $(CYGPATH_W) '$(srcdir)/src/psg.c'; fi`

src/1984-rtc.o: src/rtc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-rtc.o -MD -MP -MF src/$(DEPDIR)/1984-rtc.Tpo -c -o src/1984-rtc.o `test -f 'src/rtc.c' || echo '$(srcdir)/'`src/rtc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-rtc.Tpo src/$(DEPDIR)/1984-rtc.Po
#	$(AM_V_CC)source='src/rtc.c' object='src/1984-rtc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-rtc.o `test -f 'src/rtc.c' || echo '$(srcdir)/'`src/rtc.c

src/1984-rtc.obj: src/rtc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-rtc.obj -MD -MP -MF src/$(DEPDIR)/1984-rtc.Tpo -c -o src/1984-rtc.obj `if test -f 'src/rtc.c'; then $(CYGPATH_W) 'src/rtc.c'; else $(CYGPATH_W) '$(srcdir)/src/rtc.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-rtc.Tpo src/$(DEPDIR)/1984-rtc.Po
#	$(AM_V_CC)source='src/rtc.c' object='src/1984-rtc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-rtc.obj `if test -f 'src/rtc.c'; then $(CYGPATH_W) 'src/rtc.c'; else $(CYGPATH_W) '$(srcdir)/src/rtc.c'; fi`

src/1984-ide.o: src/ide.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-ide.o -MD -MP -MF src/$(DEPDIR)/1984-ide.Tpo -c -o src/1984-ide.o `test -f 'src/ide.c' || echo '$(srcdir)/'`src/ide.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-ide.Tpo src/$(DEPDIR)/1984-ide.Po
#	$(AM_V_CC)source='src/ide.c' object='src/1984-ide.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-ide.o `test -f 'src/ide.c' || echo '$(srcdir)/'`src/ide.c

src/1984-ide.obj: src/ide.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-ide.obj -MD -MP -MF src/$(DEPDIR)/1984-ide.Tpo -c -o src/1984-ide.obj `if test -f 'src/ide.c'; then $(CYGPATH_W) 'src/ide.c'; else $(CYGPATH_W) '$(srcdir)/src/ide.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-ide.Tpo src/$(DEPDIR)/1984-ide.Po
#	$(AM_V_CC)source='src/ide.c' object='src/1984-ide.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-ide.obj `if test -f 'src/ide.c'; then $(CYGPATH_W) 'src/ide.c'; else $(CYGPATH_W) '$(srcdir)/src/ide.c'; fi`

src/1984-z80.o: src/z80.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-z80.o -MD -MP -MF src/$(DEPDIR)/1984-z80.Tpo -c -o src/1984-z80.o `test -f 'src/z80.c' || echo '$(srcdir)/'`src/z80.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-z80.Tpo src/$(DEPDIR)/1984-z80.Po
#	$(AM_V_CC)source='src/z80.c' object='src/1984-z80.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-z80.o `test -f 'src/z80.c' || echo '$(srcdir)/'`src/z80.c

src/1984-z80.obj: src/z80.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -MT src/1984-z80.obj -MD -MP -MF src/$(DEPDIR)/1984-z80.Tpo -c -o src/1984-z80.obj `if test -f 'src/z80.c'; then $(CYGPATH_W) 'src/z80.c'; else $(CYGPATH_W) '$(srcdir)/src/z80.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/1984-z80.Tpo src/$(DEPDIR)/1984-z80.Po
#	$(AM_V_CC)source='src/z80.c' object='src/1984-z80.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(1984_CFLAGS) $(CFLAGS) -c -o src/1984-z80.obj `if test -f 'src/z80.c'; then $(CYGPATH_W) 'src/z80.c'; else $(CYGPATH_W) '$(srcdir)/src/z80.c'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	$(AM_V_at)$(MKDIR_P) "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-bzip3: distdir
	tardir=$(distdir) && $(am__tar) | bzip3 -c >$(distdir).tar.bz3
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.bz3*) \
	  bzip3 -dc $(distdir).tar.bz3 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) $(AM_DISTCHECK_DVI_TARGET) \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-$(am__rm_f) $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || $(am__rm_f) $(CONFIG_CLEAN_VPATH_FILES)
	-$(am__rm_f) src/$(DEPDIR)/$(am__dirstamp)
	-$(am__rm_f) src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f src/$(DEPDIR)/1984-config.Po
	-rm -f src/$(DEPDIR)/1984-cpc.Po
	-rm -f src/$(DEPDIR)/1984-crtc.Po
	-rm -f src/$(DEPDIR)/1984-disk.Po
	-rm -f src/$(DEPDIR)/1984-display.Po
	-rm -f src/$(DEPDIR)/1984-fdc.Po
	-rm -f src/$(DEPDIR)/1984-gate_array.Po
	-rm -f src/$(DEPDIR)/1984-joy.Po
	-rm -f src/$(DEPDIR)/1984-kbd.Po
	-rm -f src/$(DEPDIR)/1984-main.Po
	-rm -f src/$(DEPDIR)/1984-mem.Po
	-rm -f src/$(DEPDIR)/1984-monitor.Po
	-rm -f src/$(DEPDIR)/1984-net4cpc.Po
	-rm -f src/$(DEPDIR)/1984-overlay.Po
	-rm -f src/$(DEPDIR)/1984-paste.Po
	-rm -f src/$(DEPDIR)/1984-ppi.Po
	-rm -f src/$(DEPDIR)/1984-psg.Po
	-rm -f src/$(DEPDIR)/1984-rtc.Po
	-rm -f src/$(DEPDIR)/1984-ide.Po
	-rm -f src/$(DEPDIR)/1984-z80.Po
	-rm -f src/$(DEPDIR)/1984-z80dis.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f src/$(DEPDIR)/1984-config.Po
	-rm -f src/$(DEPDIR)/1984-cpc.Po
	-rm -f src/$(DEPDIR)/1984-crtc.Po
	-rm -f src/$(DEPDIR)/1984-disk.Po
	-rm -f src/$(DEPDIR)/1984-display.Po
	-rm -f src/$(DEPDIR)/1984-fdc.Po
	-rm -f src/$(DEPDIR)/1984-gate_array.Po
	-rm -f src/$(DEPDIR)/1984-joy.Po
	-rm -f src/$(DEPDIR)/1984-kbd.Po
	-rm -f src/$(DEPDIR)/1984-main.Po
	-rm -f src/$(DEPDIR)/1984-mem.Po
	-rm -f src/$(DEPDIR)/1984-monitor.Po
	-rm -f src/$(DEPDIR)/1984-net4cpc.Po
	-rm -f src/$(DEPDIR)/1984-overlay.Po
	-rm -f src/$(DEPDIR)/1984-paste.Po
	-rm -f src/$(DEPDIR)/1984-ppi.Po
	-rm -f src/$(DEPDIR)/1984-psg.Po
	-rm -f src/$(DEPDIR)/1984-rtc.Po
	-rm -f src/$(DEPDIR)/1984-z80.Po
	-rm -f src/$(DEPDIR)/1984-z80dis.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-bzip3 dist-gzip dist-lzip dist-shar dist-tarZ dist-xz \
	dist-zip dist-zstd distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

# Tell GNU make to disable its built-in pattern rules.
%:: %,v
%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
