# 1984 CPC Emulator — configuration file

[machine]
model=6128
memory=576

[roms]
os=/var/home/salvogendut/.config/1984/roms/OS_6128.ROM
basic=/var/home/salvogendut/.config/1984/roms/BASIC_1.1.ROM
amsdos=/var/home/salvogendut/.config/1984/roms/AMSDOS.ROM

[expansion_roms]
slot_1=/var/home/salvogendut/Downloads/sym41cpc/sym-romA.rom
slot_2=/var/home/salvogendut/Downloads/sym41cpc/sym-romB.rom
slot_3=/var/home/salvogendut/Downloads/sym41cpc/sym-romC.rom
slot_4=/var/home/salvogendut/Downloads/sym41cpc/sym-romD.rom
slot_5=/var/home/salvogendut/DIMITRI/Attachments-Re_ Amstrad CPC emulator/HDCPM.ROM
slot_7=/var/home/salvogendut/Downloads/UNI/unidos.rom
slot_8=/var/home/salvogendut/Downloads/UNI/unitools.rom
slot_9=/var/home/salvogendut/Downloads/UNI/fatfs-p1.rom
slot_10=/var/home/salvogendut/Downloads/UNI/fatfs-p2.rom
slot_11=/var/home/salvogendut/Downloads/UNI/albireo.rom

[board:m4]
slot_1=/var/home/salvogendut/Downloads/sym41cpc/sym-romA.rom
slot_2=/var/home/salvogendut/Downloads/sym41cpc/sym-romB.rom
slot_3=/var/home/salvogendut/Downloads/sym41cpc/sym-romC.rom
slot_4=/var/home/salvogendut/Downloads/sym41cpc/sym-romD.rom

[board:albireo]
slot_1=/var/home/salvogendut/Downloads/sym41cpc/sym-romA.rom
slot_2=/var/home/salvogendut/Downloads/sym41cpc/sym-romB.rom
slot_3=/var/home/salvogendut/Downloads/sym41cpc/sym-romC.rom
slot_4=/var/home/salvogendut/Downloads/sym41cpc/sym-romD.rom

[board:cyboard]
slot_1=/var/home/salvogendut/Downloads/sym41cpc/sym-romA.rom
slot_2=/var/home/salvogendut/Downloads/sym41cpc/sym-romB.rom
slot_3=/var/home/salvogendut/Downloads/sym41cpc/sym-romC.rom
slot_4=/var/home/salvogendut/Downloads/sym41cpc/sym-romD.rom
slot_5=/var/home/salvogendut/DIMITRI/Attachments-Re_ Amstrad CPC emulator/HDCPM.ROM
image=/var/home/salvogendut/Downloads/realcyboard.img

[storage]
drive_a=/var/home/salvogendut/Downloads/HBL/final/HBL.DSK
drive_b=/var/home/salvogendut/Downloads/ome/Arkanoid (1987)(Imagine Software)[t].dsk
tape=
external_tape=false

[hardware]
mx4=true
rom_board=true
dd1=false
m4=false
m4_path=
m4_image=
ulifac=false
net4cpc=false
net4cpc_tap=true
net4cpc_tap_host_ip=10.0.0.1
net4cpc_tap_netmask=255.255.255.0
net4cpc_tap_lease_start=10.0.0.100
net4cpc_tap_lease_end=10.0.0.150
rtc=true
symbiface_ide=true
ide_image=/var/home/salvogendut/Downloads/realcyboard.img
symbiface_mouse=true
symbnet=false
albireo=false
albireo_image=
albireo_disable_disk_read=false

[display]
scale=2
fullscreen=false
fullscreen_smoothing=true

[advanced]
tinker=true
debug=true
